FROM ubuntu:16.04
#FROM kaylanb/py3:latest

SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y \
    git \
    python3 \
    python3-pip \
    python3-venv \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /srv/py3_venv

COPY requirements_py3.txt /tmp/
RUN source /srv/py3_venv/bin/activate && \
    pip3 install --upgrade pip setuptools wheel && \
    pip3 install --requirement /tmp/requirements_py3.txt


#
COPY entrypoint_py3.sh /
ENTRYPOINT ["/entrypoint_py3.sh"]
#CMD ["/bin/bash"]
